### ISSUE TITLE
Set Up Development Environment for Nexa

### ISSUE THREAD

**Issue by vivek-pr** [vivek-pr/nexa#1]
To begin developing Nexa, our speech-based AI assistant, we need a solid development environment. This issue outlines the tasks required to set it up.

#### Tasks:

1. **Repository Initialization**:
   - [x] Create a new GitHub repository named "Nexa".
   - [x] Clone the repository to the local machine.
   
2. **Python Environment**:
   - [x] Set up a Python virtual environment.
     - Use: `python -m venv nexa_env`
   - [x] Activate the virtual environment.
     - On Windows: `nexa_env\Scripts\activate`
     - On macOS/Linux: `source nexa_env/bin/activate`
     
3. **Required Libraries**:
   - [x] Install necessary libraries for STT and TTS.
     - Example (this will depend on your final choice of tools): 
       ```bash
       pip install google-cloud-speech google-cloud-texttospeech
       ```
   - [x] Create a `requirements.txt` file to keep track of installed packages.
     - Use: `pip freeze > requirements.txt`
     
4. **Directory Structure**:
   - [x] Set up a basic directory structure for the project.
     - `/src` for source code.
     - `/data` for any data or model files.
     - `/docs` for documentation.
     - `/tests` for test scripts.

5. **Initial Commit**:
   - [x] Add all initial files to the repository.
   - [x] Commit with a message "Initial setup".
   - [x] Push the commit to GitHub.
